mysite/animalerie/urls.py
from django.urls import path

from . import views

app_name = 'animalerie'
urlpatterns = [
    path('', views.index, name='index'),
    path('controller/', views.controller, name='controller')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('animalerie/', include('animalerie.urls')),
    path('admin/', admin.site.urls),
]

mysite/animalerie/models.py
from django.db import models

# Create your models here.

class Animal(models.Model):
    AFFAME = 'AF'
    FATIGUE = 'FA'
    REPUS = 'RE'
    ENDORMI = 'EN'
    ETAT_CHOICES = (
        (AFFAME, 'affam\u00e9'),
        (FATIGUE, 'fatigu\u00e9'),
        (REPUS, 'repus'),
        (ENDORMI, 'endormi'),
    )
    NID = 'NI'
    MANGEOIRE = 'MA'
    LITIERE = 'LI'
    ROUE = 'RO'
    LIEU_CHOICES = (
        (NID, 'nid'),
        (MANGEOIRE, 'mangeoire'),
        (LITIERE, 'liti\u00e8re'),
        (ROUE, 'roue'),
    )

    animal = models.CharField(max_length=100, primary_key=True)
    race = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    etat = models.CharField(
        max_length=2,
        choices=ETAT_CHOICES,
        default=AFFAME,
    )
    lieu = models.ForeignKey(
        'Equipement',
        on_delete=models.CASCADE,
    )

    @staticmethod
    def lit_etat(name):
        try:
            anim = Animal.objects.get(animal=name)
        except Animal.DoesNotExist:
            return None
        return anim.etat

    @staticmethod
    def lit_lieu(name):
        try:
            anim = Animal.objects.get(animal=name)
        except Animal.DoesNotExist:
            return None
        return anim.lieu.lieu

    @staticmethod
    def change_etat(name, etat):
        try:
            animal = Animal.objects.get(animal=name)
        except Animal.DoesNotExist:
            return None
        for pair in animal.ETAT_CHOICES:
            if etat in pair:
                animal.etat = etat
                animal.save()

    @staticmethod
    def change_lieu(name, nlieu):
        try:
            anim = Animal.objects.get(animal=name)
        except Animal.DoesNotExist:
            return None
        try:
            new_lieu = Equipement.objects.get(lieu=nlieu)
        except Equipement.DoesNotExist:
            return None
        if new_lieu.disponibilite is True:
            old_lieu = anim.lieu
            anim.lieu = new_lieu
            if not anim.lieu.lieu == "LI":
                anim.lieu.disponibilite = False
            old_lieu.disponibilite = True
            old_lieu.save()
            anim.lieu.save()
            anim.save()

    def __str__(self):
        return self.animal


class Equipement(models.Model):
    NID = 'NI'
    MANGEOIRE = 'MA'
    LITIERE = 'LI'
    ROUE = 'RO'
    LIEU_CHOICES = (
        (NID, 'nid'),
        (MANGEOIRE, 'mangeoire'),
        (LITIERE, 'liti\u00e8re'),
        (ROUE, 'roue'),
    )

    lieu = models.CharField(
        primary_key=True,
        max_length=2,
        choices=LIEU_CHOICES,
    )
    disponibilite = models.BooleanField()

    @staticmethod
    def verifie_disponibilite(equip):
        try:
            e = Equipement.objects.get(lieu=equip)
        except Equipement.DoesNotExist:
            return None
        return e.disponibilite

    @staticmethod
    def cherche_occupant(equip):
        try:
            e = Equipement.objects.get(lieu=equip)
        except Equipement.DoesNotExist:
            return None
        e = e.animal_set.all()
        res = []
        for anim in e:
            res += [anim]
        return res

    def __str__(self):
        return self.get_lieu_display()

mysite/animalerie/views.py
from .models import Animal, Equipement
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# Create your views here.


def index(request):
    action_list = ['nourrir', 'divertir', 'coucher', 'réveiller']
    animal_list = Animal.objects.order_by('animal')
    context = {'animal_list': animal_list, 'action_list': action_list}
    return render(request, 'animalerie/index.html', context)


def controller(request):
    action_list = ['nourrir', 'divertir', 'coucher', 'réveiller']
    animal_list = Animal.objects.order_by('animal')
    animal_names = []
    for anim in animal_list:
        animal_names += [anim.animal]
    if request.POST.get('animal', False) is False or request.POST.get('action', False) is False:
        context = {'animal_list': animal_list, 'action_list': action_list, 'error_message': "You didn't select an "
                                                                                            "animal and an action.",}
        return render(request, 'animalerie/index.html', context)

    action = request.POST['action']
    name = request.POST['animal']

    if name not in animal_names or action not in action_list:
        context = {'animal_list': animal_list, 'action_list': action_list, 'error_message': "Received unknown data.", }
        return render(request, 'animalerie/index.html', context)

    if action == 'nourrir':
        message = nourrir(name)
    elif action == 'divertir':
        message = divertir(name)
    elif action == 'coucher':
        message = coucher(name)
    elif action == 'réveiller':
        message = reveiller(name)
    else:
        message = "APOCALYPSE!!!"

    if message is True:
        return HttpResponseRedirect(reverse('animalerie:index'))
    else:
        context = {'animal_list': animal_list, 'action_list': action_list, 'error_message': message, }
        return render(request, 'animalerie/index.html', context)


# here begins controller logic

def nourrir(id_animal):
    if Animal.lit_etat(id_animal) is not None:
        if Animal.lit_etat(id_animal) != 'AF':
            return 'Désolé, ' + id_animal + " n'a pas faim..."
        elif Equipement.verifie_disponibilite('MA') is False:
            occupant = Equipement.cherche_occupant('MA') # TODO: list with strings
            namestring = ""
            for ani in occupant:
                namestring += ani.animal
            return 'Impossible, la mangeoire est actuellement occupée par ' + namestring
        else:
            Animal.change_etat(id_animal, 'RE')
            Animal.change_lieu(id_animal, 'MA')
            return True
    else:
        return "Désolé, " + id_animal + " n'est pas un animal connu"


def divertir(id_animal):
    if Animal.lit_etat(id_animal) is not None:
        if Animal.lit_etat(id_animal) != 'RE':
            return 'Désolé, ' + id_animal + " n'est pas en état de faire du sport."
        elif Equipement.verifie_disponibilite('RO') is False:
            occupant = Equipement.cherche_occupant('RO')
            namestring = ""
            for ani in occupant:
                namestring += ani.animal
            return 'Impossible, la roue est actuellement occupée par ' + namestring
        else:
            Animal.change_etat(id_animal, 'FA')
            Animal.change_lieu(id_animal, 'RO')
            return True
    else:
        return "Désolé, " + id_animal + " n'est pas un animal connu"


def coucher(id_animal):
    if Animal.lit_etat(id_animal) is not None:
        if Animal.lit_etat(id_animal) != 'FA':
            return 'Désolé, ' + id_animal + " n'est pas fatigué."
        elif Equipement.verifie_disponibilite('NI') is False:
            occupant = Equipement.cherche_occupant('NI')
            namestring = ""
            for ani in occupant:
                namestring += ani.animal
            return 'Impossible, le nid est actuellement occupé par ' + namestring
        else:
            Animal.change_etat(id_animal, 'EN')
            Animal.change_lieu(id_animal, 'NI')
            return True
    else:
        return "Désolé, " + id_animal + " n'est pas un animal connu"


def reveiller(id_animal):
    if Animal.lit_etat(id_animal) is not None:
        if Animal.lit_etat(id_animal) != 'EN':
            return 'Désolé, ' + id_animal + " ne dort pas."
        else:
            Animal.change_etat(id_animal, 'AF')
            Animal.change_lieu(id_animal, 'LI')
            return True
    else:
        return "Désolé, " + id_animal + " n'est pas un animal connu"

mysite/animalerie/templates/animalerie/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'animalerie/style.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

{% if animal_list and action_list %}
<div class="container">
    <div class="animalerie">
        <div class="appRow head main">
            Bienvenue à l'animalerie
        </div>
        <div class="appRow head lower">
            Tableau de bord
        </div>
        <div class="appRow">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">nom</th>
                  <th scope="col">race</th>
                  <th scope="col">type</th>
                  <th scope="col">état</th>
                  <th scope="col">lieu</th>
                </tr>
              </thead>
              <tbody>
                {% for animal in animal_list %}
                <tr>
                  <td>{{ animal.animal }}</td>
                  <td>{{ animal.race }}</td>
                  <td>{{ animal.type }}</td>
                  <td>{{ animal.get_etat_display }}</td>
                  <td>{{ animal.lieu.get_lieu_display }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
        <div class="appRow head lower">
            Actions
        </div>
        <div class="appRow">
            <form action="{% url 'animalerie:controller' %}" method="post">
            {% csrf_token %}
            <div class="appRow">
              <div class="form-row">
                <div class="col">
                  <fieldset class="form-group subradios">
                    <div class="row">
                      <legend class="col-form-label col-sm-3 pt-0">Animal</legend>
                      <div class="col-sm-10">
                        {% for animal in animal_list %}
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="animal" id="Radio{{ animal.animal }}" value="{{ animal.animal }}">
                                <label class="form-check-label" for="Radio{{ animal.animal }}">
                                    {{ animal.animal }}
                                </label>
                            </div>
                        {% endfor %}
                      </div>
                    </div>
                  </fieldset>
                </div>
                <div class="col">
                  <fieldset class="form-group subradios">
                    <div class="row">
                      <legend class="col-form-label col-sm-3 pt-0">Action</legend>
                      <div class="col-sm-10">
                        {% for actions in action_list %}
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="action" id="{{ actions }}Radio" value="{{ actions }}">
                                <label class="form-check-label" for="{{ actions }}Radio">
                                    {{ actions }}
                                </label>
                            </div>
                        {% endfor %}
                      </div>
                    </div>
                  </fieldset>
                </div>
              </div>
              {% if error_message %}<div class="appRow warning"><strong>{{ error_message }}</strong></div>{% endif %}
            </div>
                <div class="form-group row myButton">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Go!</button>
                </div>
                </div>
            </form>
        </div>

    </div>
{% else %}
    <p>No animals or actions available.</p>
{% endif %}
</div>